# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='at_ring',
            field=models.BooleanField(default=False),
        ),
    ]
