# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_teammatch_at_ring'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistrationError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_text', models.TextField()),
                ('school_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.SchoolRegistration')),
            ],
        ),
    ]
