# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-24 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0003_schoolregistrationerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='competing',
            field=models.BooleanField(default=False),
        ),
    ]
