# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-29 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0005_rename_teammatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamRegistration',
            new_name='SparringTeamRegistration',
        ),
    ]
