# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-29 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0008_rename_tournament_division'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Division',
            new_name='SparringDivision',
        ),
    ]
