# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-29 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0009_rename_division'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolRegistration',
            new_name='SchoolTournamentRegistration',
        ),
        migrations.RenameModel(
            old_name='SchoolRegistrationError',
            new_name='SchoolTournamentRegistrationError',
        ),
    ]
