# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def create_school_season_registrations(apps, schema_editor):
    """Copy SchoolTournamentRegistration to SchoolSeasonRegistration"""
    SchoolTournamentRegistration = apps.get_model(
            "tmdb", "SchoolTournamentRegistration")
    SchoolSeasonRegistration = apps.get_model(
            "tmdb", "SchoolSeasonRegistration")
    for tournament_reg in SchoolTournamentRegistration.objects.all():
        season_reg, created = SchoolSeasonRegistration.objects.get_or_create(
                school=tournament_reg.school,
                season=tournament_reg.tournament.season,
                division=3)
        tournament_reg.school_season_registration = season_reg
        tournament_reg.save()

def delete_school_season_registrations(apps, schema_editor):
    SchoolTournamentRegistration = apps.get_model(
            "tmdb", "SchoolTournamentRegistration")
    for tournament_reg in SchoolTournamentRegistration.objects.all():
        tournament_reg.school_season_registration = None
        tournament_reg.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0012_add_tournament_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='tournaments',
        ),
        migrations.CreateModel(
            name='SchoolSeasonRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.PositiveSmallIntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.School')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.Season')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='seasons',
            field=models.ManyToManyField(through='tmdb.SchoolSeasonRegistration', to='tmdb.Season'),
        ),
        migrations.AddField(
            model_name='season',
            name='schools',
            field=models.ManyToManyField(through='tmdb.SchoolSeasonRegistration', to='tmdb.School'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolseasonregistration',
            unique_together=set([('season', 'school')]),
        ),
        migrations.AddField(
            model_name='SchoolTournamentRegistration',
            name='school_season_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tmdb.SchoolSeasonRegistration'),
        ),
        migrations.AlterUniqueTogether(
            name='schooltournamentregistration',
            unique_together=set([('tournament', 'school_season_registration')]),
        ),
        migrations.RunPython(create_school_season_registrations,
                delete_school_season_registrations),
        migrations.AlterField(
            model_name='schooltournamentregistration',
            name='school_season_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.SchoolSeasonRegistration'),
        ),
        migrations.AlterField(
            model_name='schooltournamentregistration',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tmdb.School'),
        ),
    ]
