# Generated by Django 2.2 on 2019-04-10 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0015_season_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolseasonregistration',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.School'),
        ),
        migrations.AlterField(
            model_name='schoolseasonregistration',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.Season'),
        ),
        migrations.AlterField(
            model_name='schooltournamentregistration',
            name='school_season_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.SchoolSeasonRegistration'),
        ),
        migrations.AlterField(
            model_name='sparringteam',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.SparringDivision'),
        ),
        migrations.AlterField(
            model_name='sparringteam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.School'),
        ),
        migrations.AlterField(
            model_name='sparringteammatch',
            name='blue_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_team', to='tmdb.SparringTeamRegistration'),
        ),
        migrations.AlterField(
            model_name='sparringteammatch',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.TournamentSparringDivision'),
        ),
        migrations.AlterField(
            model_name='sparringteammatch',
            name='red_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_team', to='tmdb.SparringTeamRegistration'),
        ),
        migrations.AlterField(
            model_name='sparringteammatch',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_team', to='tmdb.SparringTeamRegistration'),
        ),
        migrations.AlterField(
            model_name='sparringteamregistration',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.SparringTeam'),
        ),
        migrations.AlterField(
            model_name='sparringteamregistration',
            name='tournament_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.TournamentSparringDivision'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.Season'),
        ),
        migrations.AlterField(
            model_name='tournamentsparringdivision',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.SparringDivision'),
        ),
        migrations.AlterField(
            model_name='tournamentsparringdivision',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmdb.Tournament'),
        ),
    ]
