# Generated by Django 2.2.4 on 2019-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0018_modify_on_deletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparringteamregistration',
            name='has_alternate1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparringteamregistration',
            name='has_alternate2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparringteamregistration',
            name='has_heavyweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparringteamregistration',
            name='has_lightweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparringteamregistration',
            name='has_middleweight',
            field=models.BooleanField(default=False),
        ),
    ]
