# Generated by Django 2.2.4 on 2019-08-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0020_set_weightclass_booleans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparringteamregistration',
            name='alternate1',
        ),
        migrations.RemoveField(
            model_name='sparringteamregistration',
            name='alternate2',
        ),
        migrations.RemoveField(
            model_name='sparringteamregistration',
            name='heavyweight',
        ),
        migrations.RemoveField(
            model_name='sparringteamregistration',
            name='lightweight',
        ),
        migrations.RemoveField(
            model_name='sparringteamregistration',
            name='middleweight',
        ),
    ]
