# Generated by Django 2.2.4 on 2019-08-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0021_delete_weightclass_fks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competitor',
        ),
    ]
