# Generated by Django 2.2.4 on 2019-08-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0022_delete_competitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparringteamregistration',
            old_name='has_alternate1',
            new_name='alternate1',
        ),
        migrations.RenameField(
            model_name='sparringteamregistration',
            old_name='has_alternate2',
            new_name='alternate2',
        ),
        migrations.RenameField(
            model_name='sparringteamregistration',
            old_name='has_heavyweight',
            new_name='heavyweight',
        ),
        migrations.RenameField(
            model_name='sparringteamregistration',
            old_name='has_lightweight',
            new_name='lightweight',
        ),
        migrations.RenameField(
            model_name='sparringteamregistration',
            old_name='has_middleweight',
            new_name='middleweight',
        ),
    ]
