# Generated by Django 2.2.6 on 2019-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0024_allow_null_registration_doc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='short_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
